In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("/content/dataset.csv")
df.size

2323

In [ ]:
df.head()

ID  AGE  PackHistory COPDSEVERITY  MWT1  MWT2  MWT1Best  FEV1  FEV1PRED  \
0   58   77         60.0       SEVERE   120   120       120  1.21      36.0   
1   57   79         50.0     MODERATE   165   176       176  1.09      56.0   
2   62   80         11.0     MODERATE   201   180       201  1.52      68.0   
3  145   56         60.0  VERY SEVERE   210   210       210  0.47      14.0   
4  136   65         68.0       SEVERE   204   210       210  1.07      42.0   

    FVC  ...   SGRQ  AGEquartiles  copd  gender  smoking  Diabetes  muscular  \
0  2.40  ...  69.55             4     3       1        2         1         0   
1  1.64  ...  44.24             4     2       0        2         1         0   
2  2.30  ...  44.09             4     2       0        2         1         0   
3  1.14  ...  62.04             1     4       1        2         0         0   
4  2.91  ...  75.56             1     3       1        2         0         1   

   hypertension  AtrialFib  IHD  
0             0          1    0  
1             0          1    1  
2             0          1    0  
3             1          1    0  
4             1          0    0  

[5 rows x 23 columns]

In [ ]:
df.tail()

ID  AGE  PackHistory COPDSEVERITY  MWT1  MWT2  MWT1Best  FEV1  FEV1PRED  \
96    10   68         25.0         MILD   511   575       575  2.70      98.0   
97    43   75         40.0         MILD   576   577       577  2.90      93.0   
98    74   68         30.0     MODERATE   468   582       582  1.65      67.0   
99   108   54         30.0       SEVERE   688   699       699  1.72      44.0   
100   85   78         55.0     MODERATE   490   570       570  1.15      54.0   

      FVC  ...   SGRQ  AGEquartiles  copd  gender  smoking  Diabetes  \
96   3.87  ...  35.84             2     1       1        2         0   
97   4.72  ...  15.05             3     1       1        2         0   
98   2.80  ...  19.70             2     2       0        2         0   
99   4.07  ...  20.55             1     3       1        2         0   
100  2.01  ...  30.21             4     2       1        2         0   

     muscular  hypertension  AtrialFib  IHD  
96          1             0          0    0  
97          1             0          0    1  
98          0             1          0    0  
99          0             0          0    0  
100         0             0          0    0  

[5 rows x 23 columns]

In [ ]:
df.isnull().any()

ID              False
AGE             False
PackHistory     False
COPDSEVERITY    False
MWT1            False
MWT2            False
MWT1Best        False
FEV1            False
FEV1PRED        False
FVC             False
FVCPRED         False
CAT             False
HAD             False
SGRQ            False
AGEquartiles    False
copd            False
gender          False
smoking         False
Diabetes        False
muscular        False
hypertension    False
AtrialFib       False
IHD             False
dtype: bool

In [ ]:
df.head()

ID  AGE  PackHistory COPDSEVERITY  MWT1  MWT2  MWT1Best  FEV1  FEV1PRED  \
0   58   77         60.0       SEVERE   120   120       120  1.21      36.0   
1   57   79         50.0     MODERATE   165   176       176  1.09      56.0   
2   62   80         11.0     MODERATE   201   180       201  1.52      68.0   
3  145   56         60.0  VERY SEVERE   210   210       210  0.47      14.0   
4  136   65         68.0       SEVERE   204   210       210  1.07      42.0   

    FVC  ...   SGRQ  AGEquartiles  copd  gender  smoking  Diabetes  muscular  \
0  2.40  ...  69.55             4     3       1        2         1         0   
1  1.64  ...  44.24             4     2       0        2         1         0   
2  2.30  ...  44.09             4     2       0        2         1         0   
3  1.14  ...  62.04             1     4       1        2         0         0   
4  2.91  ...  75.56             1     3       1        2         0         1   

   hypertension  AtrialFib  IHD  
0             0          1    0  
1             0          1    1  
2             0          1    0  
3             1          1    0  
4             1          0    0  

[5 rows x 23 columns]

In [ ]:
X=df.drop(['COPDSEVERITY','copd'],axis=1)
y=df['copd']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
from sklearn.linear_model import LogisticRegression
cl=LogisticRegression(solver='liblinear')
cl.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [ ]:
y_test_hat=cl.predict(x_test)
res=pd.DataFrame({'actual':y_test,'pred':y_test_hat})
res.head()

actual  pred
67       3     3
29       3     4
54       3     4
45       1     3
0        3     3

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_test_hat))
print(classification_report(y_test,y_test_hat))

[[3 2 1 0]
 [0 4 0 0]
 [0 2 3 4]
 [0 0 2 0]]
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         6
           2       0.50      1.00      0.67         4
           3       0.50      0.33      0.40         9
           4       0.00      0.00      0.00         2

    accuracy                           0.48        21
   macro avg       0.50      0.46      0.43        21
weighted avg       0.60      0.48      0.49        21



In [ ]:
from sklearn.tree import DecisionTreeClassifier
cl=DecisionTreeClassifier()
cl.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_test_hat=cl.predict(x_test)
res=pd.DataFrame({'act':y_test,'pred':y_test_hat})
res.head()

act  pred
67    3     3
29    3     3
54    3     3
45    1     1
0     3     3

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_test_hat))
print(classification_report(y_test,y_test_hat))

[[5 1 0 0]
 [1 3 0 0]
 [0 0 9 0]
 [0 0 0 2]]
              precision    recall  f1-score   support

           1       0.83      0.83      0.83         6
           2       0.75      0.75      0.75         4
           3       1.00      1.00      1.00         9
           4       1.00      1.00      1.00         2

    accuracy                           0.90        21
   macro avg       0.90      0.90      0.90        21
weighted avg       0.90      0.90      0.90        21



In [ ]:
feature_importances=pd.DataFrame(cl.feature_importances_,index=x_train.columns,columns=['importance']).sort_values('importance')
feature_importances

importance
ID              0.000000
hypertension    0.000000
muscular        0.000000
smoking         0.000000
gender          0.000000
AGEquartiles    0.000000
SGRQ            0.000000
HAD             0.000000
AtrialFib       0.000000
CAT             0.000000
FEV1            0.000000
MWT1Best        0.000000
MWT2            0.000000
PackHistory     0.000000
FVCPRED         0.000000
IHD             0.000000
Diabetes        0.025217
AGE             0.035012
MWT1            0.036855
FVC             0.058839
FEV1PRED        0.844077

In [ ]:
from sklearn.ensemble import RandomForestClassifier
cl=RandomForestClassifier()
cl.fit(x_train,y_train)
y_test_hat=cl.predict(x_test)
res=pd.DataFrame({'act':y_test,'pred':y_test_hat})
res.head()

act  pred
67    3     3
29    3     3
54    3     3
45    1     2
0     3     3

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_test_hat))
print(classification_report(y_test,y_test_hat))

[[4 2 0 0]
 [0 4 0 0]
 [0 0 9 0]
 [0 0 2 0]]
              precision    recall  f1-score   support

           1       1.00      0.67      0.80         6
           2       0.67      1.00      0.80         4
           3       0.82      1.00      0.90         9
           4       0.00      0.00      0.00         2

    accuracy                           0.81        21
   macro avg       0.62      0.67      0.62        21
weighted avg       0.76      0.81      0.77        21



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
feature_importances=pd.DataFrame(cl.feature_importances_,index=x_train.columns,columns=['importance']).sort_values('importance')
feature_importances

importance
IHD             0.000313
hypertension    0.002638
AtrialFib       0.003075
muscular        0.004756
Diabetes        0.006136
smoking         0.007622
gender          0.008729
AGEquartiles    0.011246
HAD             0.024181
AGE             0.027710
SGRQ            0.029176
CAT             0.030455
ID              0.036134
MWT1Best        0.039577
PackHistory     0.045748
MWT2            0.047253
MWT1            0.052912
FVC             0.065856
FVCPRED         0.095390
FEV1            0.117853
FEV1PRED        0.343239

In [ ]:
from sklearn.naive_bayes import GaussianNB
cl=GaussianNB()
cl.fit(x_train,y_train)
y_test_hat=cl.predict(x_test)
res=pd.DataFrame({'act':y_test,'pred':y_test_hat})
res.head()

act  pred
67    3     3
29    3     2
54    3     3
45    1     3
0     3     3

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_test_hat))
print(classification_report(y_test,y_test_hat))

[[3 2 1 0]
 [0 4 0 0]
 [0 1 8 0]
 [0 0 0 2]]
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         6
           2       0.57      1.00      0.73         4
           3       0.89      0.89      0.89         9
           4       1.00      1.00      1.00         2

    accuracy                           0.81        21
   macro avg       0.87      0.85      0.82        21
weighted avg       0.87      0.81      0.81        21



In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
label=le.fit_transform(df['copd'])
label

array([2, 1, 1, 3, 2, 1, 2, 2, 1, 2, 2, 3, 3, 0, 1, 1, 2, 1, 3, 3, 3, 3,
       2, 2, 0, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 2,
       1, 0, 2, 1, 1, 0, 1, 0, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 2, 0, 2, 0, 3, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 2, 2, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 1])

In [ ]:
df.drop('copd',axis=1,inplace=True)
df['copd']=label

In [ ]:
X=df.drop(['COPDSEVERITY','copd'],axis=1)
y=df['copd']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
from xgboost import XGBClassifier
cl=XGBClassifier()
cl.fit(x_train,y_train)
y_test_hat=cl.predict(x_test)
res=pd.DataFrame({'act':y_test,'pred':y_test_hat})
res.head()

act  pred
43    2     2
27    1     1
67    2     2
49    0     0
79    0     0

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_test_hat))
print(classification_report(y_test,y_test_hat))

[[4 2 0 0]
 [0 7 0 0]
 [0 0 5 0]
 [0 0 0 3]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         6
           1       0.78      1.00      0.88         7
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         3

    accuracy                           0.90        21
   macro avg       0.94      0.92      0.92        21
weighted avg       0.93      0.90      0.90        21



In [ ]:
feature_importances=pd.DataFrame(cl.feature_importances_,index=x_train.columns,columns=['importance']).sort_values('importance')
feature_importances

importance
IHD             0.000000
hypertension    0.000000
muscular        0.000000
Diabetes        0.000000
smoking         0.000000
AGEquartiles    0.000000
SGRQ            0.000000
AtrialFib       0.000000
MWT1            0.000829
CAT             0.011791
HAD             0.018708
FVCPRED         0.018750
MWT2            0.020494
ID              0.023031
MWT1Best        0.024899
PackHistory     0.027375
FVC             0.031434
gender          0.052319
FEV1            0.101139
AGE             0.162148
FEV1PRED        0.507083

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("/content/dataset.csv")
df.size

In [ ]:
X=df.drop(['COPDSEVERITY','copd'],axis=1)
y=df['copd']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
model = Sequential()
model.add(Dense(units=11, input_shape = (X.shape[1],), activation='relu', kernel_initializer = 'he_normal'))
model.add(Dense(units = 10, activation = 'relu', kernel_initializer = 'he_normal'))
model.add(Dropout(0.3))
model.add(Dense(units = 10, activation = 'relu', kernel_initializer = 'he_normal'))
model.add(Dropout(0.3))
model.add(Dense(units = 1, activation = 'sigmoid'))

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, epochs = 100, batch_size = 25, verbose = 1, validation_data=(x_test, y_test))

Epoch 1/100
4/4 [==============================] - 1s 69ms/step - loss: 0.5074 - accuracy: 0.4000 - val_loss: -0.0251 - val_accuracy: 0.4762
Epoch 2/100
4/4 [==============================] - 0s 12ms/step - loss: 0.6147 - accuracy: 0.3750 - val_loss: -0.0446 - val_accuracy: 0.4762
Epoch 3/100
4/4 [==============================] - 0s 13ms/step - loss: 0.4665 - accuracy: 0.3875 - val_loss: -0.0622 - val_accuracy: 0.4762
Epoch 4/100
4/4 [==============================] - 0s 13ms/step - loss: 0.2938 - accuracy: 0.4375 - val_loss: -0.0852 - val_accuracy: 0.4762
Epoch 5/100
4/4 [==============================] - 0s 13ms/step - loss: 0.5387 - accuracy: 0.3500 - val_loss: -0.1083 - val_accuracy: 0.4762
Epoch 6/100
4/4 [==============================] - 0s 13ms/step - loss: 0.4041 - accuracy: 0.4000 - val_loss: -0.1325 - val_accuracy: 0.4762
Epoch 7/100
4/4 [==============================] - 0s 13ms/step - loss: 0.2765 - accuracy: 0.3625 - val_loss: -0.1586 - val_accuracy: 0.4762
Epoch 8/100
4

In [ ]:
loss, acc = model.evaluate(x_test, y_test)
print('Accuracy of model is : %.3f' %acc)

1/1 [==============================] - 0s 27ms/step - loss: -57.5310 - accuracy: 0.4762
Accuracy of model is : 0.476
